# Dependencies

highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Keisa McGrew
tagline:          'Genealogy, Planted Tanks and Stuff'
description:      'Genealogy, Planted Tanks and Stuff'
url:              http://keisa.github.io/hyde/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
